name: tfsec

on: [push]

jobs:
  tfsec:
    name: Run tfsec report
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          format: json

      - name: Upload file
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: tfsec-findings
          path: tfsec.json
